version: '2'
services:
  web:
    build:
      context: .
      dockerfile: ./compose/isodur/Dockerfile
    container_name: isodur
    command: uwsgi --socket :8000 --module isodur.wsgi
    expose:
      - 8000

  nginx:
    build: ./compose/nginx
    expose:
      - 8000
    ports:
      - 8001:8001
    volumes:
      - ./:/isodur
    volumes_from:
      - web
